version: '3.4'

volumes:
  minio-data:
    driver: local

services:
  scrapper:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
    env_file: .env
    command: npm start
    ports:
      - 3000:3000
      - 9229:9229
